---
title: "CV"
---
# Rasmus Bejder
Olofströmsvägen 870-52\
295-94 Näsum \
Mobil. 0766063035 \
bejderpost@gmail.com\
----------------------------------------------------------------------------------------------------------------------------------------

## Erfarenheter

Praktisk: Goda datorvanor av MS Office, Adobe, Windows, Ubuntu, ERP- och CRM-system. Erfarenhet av Kundtjänst, försäljning, ärendehantering, IT-support och träning. Självständig och har en god arbetsmoral. Erfarenhet av planering, utbildning och personalhantering.\

Soft skills: Lyssnar aktivt och kommunicerar bra. Problemlösare, lagspelare och oberoende, nyfiken och kreativ. Flexibel, noggrann, ordningsam, trevlig, punktlig och pålitlig.

## Utbildning
10:e klass, avslutat 1997 \
Gymnasium, 3 år, VUC Syd, avslutat 2004 \
Skov- og naturassistent (Forest and Nature Assistant), avslutat 2013\

### Andra kurser
    • Introduktion till HTML och CSS
    • Körkort B
    • Befälsutbildning

### Språk
    • Modersmål Danska
    • Talar och skriver Engelska, Svenska och Tyska

## Arbetserfarenhet
Säljare, [Uniq Dialog](https://uniqdialog.se/){target="_blank"}, Malmö\ 
Januari 2024 – februari 2025  Tel: 040-608 58 00\

Vikarie på [Ecco](https://se.ecco.com/){target="_blank"} lager i Tønder, Danmark\
11.01.2022 till 25.05.2022

Trädgårdsservice och landskapsarkitektur på Arbejdskraft i Gørding, Danmark\
Från 03/05-2021 till 30/11-2021

Case Manager / Operations Associate, [AXA Partners](https://www.axapartners.fi/en){target="_blank"}, Helsingfors\
Oktober 2019 - april 2021\


Vildmarksguide / Slädhundsförare\
2013/14 Arctic Huskyfarm, Pyhä/Luosto\
2017 [Lapland Safaris](https://www.laplandsafaris.com/en){target="_blank"}\
2017/18 [Finn-Jann Huskyfarm Oy](https://www.finn-jann.com/){target="_blank"}\

Kundtjänstmedarbetare, [Teleperformance](https://www.teleperformance.com/en-us/){target="_blank"}, Söderhamn\
April 2010 - december 2010

IT-support och kundtjänstmedarbetare, IBM Ireland\
Februari 2008 - december 2008 Tel: +353 815 8000